version: '3'
services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DB_USER_NAME: "postgres"
      DB_PASSWORD: "password"
      DB_PORT: 5432
      DB_NAME: "test"
    links:
      - "db"
