version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      TZ: Asia/Tokyo
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
  server:
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      DB_URL: "postgresql://localhost:5432/test?user=postgres&password=password"
    links:
      - "postgres"
