DROP TABLE IF EXISTS atcoder;
CREATE TABLE atcoder (
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  range VARCHAR(255) NOT NULL,
);

DROP TABLE IF EXISTS codeforces;
CREATE TABLE codeforces (
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
);

DROP TABLE IF EXISTS yukicoder;
CREATE TABLE yukicoder (
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
);
