DROP TABLE IF EXISTS atcoder;
CREATE TABLE atcoder (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  range VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS codeforces;
CREATE TABLE codeforces (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE IF EXISTS yukicoder;
CREATE TABLE yukicoder (
  id SERIAL,
  name VARCHAR(255) NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE  NOT NULL,
  PRIMARY KEY (id)
);
