name: Test CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Set up
        uses: actions/setup-go@v2
        with:
          go-versino: 1.16

      - name: Checkout
        uses: actions/checkout@v2

      - name: init DB
        run: psql -f ./config/init.sql postgres://postgres:password@localhost:5432/test

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test code
        env:
          "DB_HOST": "postgres"
          "DB_USER_NAME": "postgres"
          "DB_PASSWORD": "password"
          "DB_PORT": "5432"
          "DB_NAME": "test"
          "LINE_CHANNEL_SECRET": "dummy_channel_secret"
          "LINE_CHANNEL_TOKEN": "dummy_channel_token"
        run: go test -v ./...
